Vagrant.require_plugin('vagrant-hostmanager')

domain = 'coe.dell.com'

# setup the cluster
nodes = [
  { :hostname => 'node1', :ip => '10.125.0.11', :box => 'ubuntu1204-chef'},
  { :hostname => 'node2', :ip => '10.125.0.12', :box => 'ubuntu1204-chef'},
  { :hostname => 'node3', :ip => '10.125.0.13', :box => 'ubuntu1204-chef'}
]

Vagrant.configure("2") do |config|
  # configure hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      # configure the box, hostname and networking 
      node_config.vm.box = node[:box]
      node_config.vm.hostname = node[:hostname] + '.' + domain
      node_config.vm.network :private_network, ip: node[:ip]
      node_config.hostmanager.aliases = node[:hostname]
          
      # use the Chef provisioner to install RabbitMQ    
      node_config.vm.provision :chef_solo do |chef|
       chef.add_recipe "rabbitmq"
       chef.add_recipe "rabbitmq::mgmt_console"
      end
    end
  end
end
